In [76]:
import pandas as pd
xls = pd.ExcelFile('Excel_test_dlouhy.xlsx')
vyroba = pd.read_csv('Excel_test_dlouhy.csv', sep = ';')
sklad = pd.read_excel(xls, 'sklad_08_2018')
z_ceho = pd.read_excel(xls, 'matice_vyroby')
vyroba_kopie=vyroba.copy()

# Ležák = v závodě se přes 2 měsíce z komponentu nic nevyrobilo

# 3 datasety pro každý závod

In [77]:
vyroba['Datum']=pd.to_datetime(vyroba['Datum'])
vybrane_mesice=vyroba.loc[(vyroba['Datum']>='2018-08-01') & (vyroba['Datum']<'2018-09-30')]
vybrane_mesice

     ID_produktu ID_zavodu      Datum  Mnozstvi
3          ND118      ZP20 2018-08-08         1
20         ND118      ZP20 2018-08-06        23
23         ND115      ZP20 2018-08-22        13
51         ND114      ZP10 2018-09-03        26
64         ND112      ZP30 2018-09-07        26
...          ...       ...        ...       ...
2030       ND110      ZP30 2018-08-03        13
2037       ND121      ZP10 2018-08-13        12
2095       ND110      ZP30 2018-08-25         7
2137       ND112      ZP10 2018-08-25        23
2146       ND118      ZP10 2018-08-02        13

[117 rows x 4 columns]

In [78]:
plzen=vybrane_mesice.loc[vybrane_mesice['ID_zavodu']=='ZP10']
prerov=vybrane_mesice.loc[vybrane_mesice['ID_zavodu']=='ZP20']
ostrava=vybrane_mesice.loc[vybrane_mesice['ID_zavodu']=='ZP30']
prerov

     ID_produktu ID_zavodu      Datum  Mnozstvi
3          ND118      ZP20 2018-08-08         1
20         ND118      ZP20 2018-08-06        23
23         ND115      ZP20 2018-08-22        13
71         ND119      ZP20 2018-08-14        11
87         ND104      ZP20 2018-08-07        24
184        ND124      ZP20 2018-08-07        19
202        ND118      ZP20 2018-08-21        10
224        ND117      ZP20 2018-08-01        21
295        ND120      ZP20 2018-08-13        17
396        ND118      ZP20 2018-08-03         8
408        ND111      ZP20 2018-08-15         3
419        ND108      ZP20 2018-08-30        15
443        ND104      ZP20 2018-08-28        28
484        ND109      ZP20 2018-08-25         3
504        ND115      ZP20 2018-08-05        16
509        ND116      ZP20 2018-08-21        28
640        ND107      ZP20 2018-08-24        29
699        ND102      ZP20 2018-08-25        23
811        ND116      ZP20 2018-08-25        25
827        ND123      ZP20 2018-08-17        27
866        ND110      ZP20 2018-09-04        20
931        ND116      ZP20 2018-08-20        13
1046       ND124      ZP20 2018-09-03         9
1127       ND103      ZP20 2018-08-29        18
1229       ND101      ZP20 2018-08-31        29
1268       ND120      ZP20 2018-08-03         4
1289       ND124      ZP20 2018-09-02        23
1434       ND119      ZP20 2018-08-08        25
1484       ND103      ZP20 2018-08-22         4
1508       ND106      ZP20 2018-08-18        14
1601       ND106      ZP20 2018-08-23         2
1681       ND120      ZP20 2018-09-04        13
1735       ND112      ZP20 2018-08-15        11
1745       ND102      ZP20 2018-08-06         3
1821       ND107      ZP20 2018-08-16         7
1970       ND117      ZP20 2018-08-18        15
1973       ND122      ZP20 2018-09-04         5

# Komponenty v závodech (k 1.8.2018)

In [81]:
import numpy as np
conditions = [
    (sklad['ID_skladu'] == 'SK01') | (sklad['ID_skladu'] == 'SK11')| (sklad['ID_skladu'] == 'SK86A'),
    (sklad['ID_skladu'] == 'SK56') | (sklad['ID_skladu'] == 'SK97'),
    (sklad['ID_skladu'] == 'SK00') | (sklad['ID_skladu'] == 'SK02')]
values=['ZP10','ZP20','ZP30']
sklad['ID_zavodu']=np.select(conditions,values)
sklad_plzen=sklad.loc[sklad['ID_zavodu']=='ZP10']
sklad_prerov=sklad.loc[sklad['ID_zavodu']=='ZP20']
sklad_ostrava=sklad.loc[sklad['ID_zavodu']=='ZP30']
sklad_ostrava

    ID_skladu ID_komponenty  Mnozstvi Stav_ke_dni ID_zavodu
1        SK00         KO037        47  2018-08-01      ZP30
7        SK02         KO094        27  2018-08-01      ZP30
8        SK02         KO168         7  2018-08-01      ZP30
9        SK02         KO171        25  2018-08-01      ZP30
12       SK00         KO120        19  2018-08-01      ZP30
17       SK00         KO160         4  2018-08-01      ZP30
18       SK02         KO083         3  2018-08-01      ZP30
24       SK00         KO090        36  2018-08-01      ZP30
25       SK02         KO034         9  2018-08-01      ZP30
32       SK02         KO202         3  2018-08-01      ZP30
33       SK02         KO132         4  2018-08-01      ZP30
35       SK02         KO004         1  2018-08-01      ZP30
42       SK00         KO206         4  2018-08-01      ZP30
46       SK02         KO047         9  2018-08-01      ZP30
52       SK00         KO024         1  2018-08-01      ZP30
57       SK00         KO110         2  2018-08-01      ZP30
95       SK00         ND102         3  2018-08-01      ZP30
96       SK00         ND103         1  2018-08-01      ZP30
97       SK00         ND104        10  2018-08-01      ZP30
98       SK02         ND105         9  2018-08-01      ZP30
99       SK02         ND108         2  2018-08-01      ZP30
100      SK02         ND109        21  2018-08-01      ZP30
101      SK00         ND110        24  2018-08-01      ZP30
102      SK00         ND112        18  2018-08-01      ZP30
103      SK02         ND113         3  2018-08-01      ZP30
104      SK00         ND118         7  2018-08-01      ZP30
105      SK00         ND122        25  2018-08-01      ZP30
106      SK00         ND123        21  2018-08-01      ZP30
107      SK02         ND124        16  2018-08-01      ZP30
108      SK02         ND122        23  2018-08-01      ZP30
109      SK02         ND123        17  2018-08-01      ZP30
110      SK02         ND124        19  2018-08-01      ZP30
116      SK02         ND107         6  2018-08-01      ZP30
117      SK00         ND111        10  2018-08-01      ZP30
118      SK02         ND114        32  2018-08-01      ZP30
119      SK00         ND116        40  2018-08-01      ZP30
120      SK00         ND119        45  2018-08-01      ZP30

In [44]:
komp={}
for x in z_ceho['ID_komponenty']:
    komp[x]=0
komp_plzen=komp.copy()
komp_ostrava=komp.copy()
komp_prerov=komp.copy()

# Kolik komponentů se využilo za 2 měsíce v každém závodu

In [45]:
for index,komp in enumerate(plzen['ID_produktu']):
    for dil in z_ceho.loc[z_ceho['ID_produktu']==komp]['ID_komponenty']:
        komp_plzen[dil]+=int(z_ceho.loc[(z_ceho['ID_komponenty']==dil) & (z_ceho['ID_produktu']==komp)]['Mnozstvi'])*(int(plzen.iloc[index,3]))

for index,komp in enumerate(prerov['ID_produktu']):
    for dil in z_ceho.loc[z_ceho['ID_produktu']==komp]['ID_komponenty']:
        komp_prerov[dil]+=int(z_ceho.loc[(z_ceho['ID_komponenty']==dil) & (z_ceho['ID_produktu']==komp)]['Mnozstvi'])*(int(prerov.iloc[index,3]))

for index,komp in enumerate(ostrava['ID_produktu']):
    for dil in z_ceho.loc[z_ceho['ID_produktu']==komp]['ID_komponenty']:
        komp_ostrava[dil]+=int(z_ceho.loc[(z_ceho['ID_komponenty']==dil) & (z_ceho['ID_produktu']==komp)]['Mnozstvi'])*(int(ostrava.iloc[index,3]))
komp_plzen

{'KO043': 66,
 'KO124': 0,
 'KO193': 0,
 'KO120': 0,
 'KO160': 0,
 'KO167': 0,
 'KO136': 25,
 'KO145': 50,
 'KO038': 50,
 'KO155': 25,
 'KO052': 50,
 'KO168': 66,
 'KO190': 33,
 'KO064': 283,
 'KO195': 250,
 'KO111': 62,
 'KO135': 6,
 'KO028': 129,
 'KO040': 86,
 'KO094': 43,
 'KO019': 86,
 'KO029': 74,
 'KO021': 111,
 'KO108': 32,
 'KO196': 48,
 'KO060': 0,
 'KO182': 56,
 'KO132': 116,
 'KO034': 0,
 'KO147': 58,
 'KO172': 58,
 'KO128': 58,
 'KO127': 51,
 'KO151': 51,
 'KO202': 51,
 'KO159': 28,
 'KO020': 28,
 'KO142': 16,
 'KO090': 8,
 'KO087': 171,
 'KO018': 237,
 'KO203': 57,
 'KO164': 42,
 'KO037': 14,
 'KO073': 28,
 'KO042': 0,
 'KO148': 0,
 'KO174': 132,
 'KO054': 132,
 'KO129': 39,
 'KO134': 37,
 'KO177': 112,
 'KO089': 112,
 'KO044': 306,
 'KO146': 58,
 'KO031': 116,
 'KO070': 124,
 'KO012': 124,
 'KO001': 38,
 'KO171': 76,
 'KO083': 21,
 'KO169': 14,
 'KO078': 24}

# Zboží co jsou ležáci vůči lokalitám (pokud komponent > 0 tzn. zůstává ve skladu) (platí pouze pro KO---)

In [74]:
for index,x in enumerate(sklad_plzen['ID_komponenty']):
    if x in komp_plzen:
        sklad_plzen.iloc[index,2]=sklad_plzen.iloc[index,2]-komp_plzen[x]
        
for index,x in enumerate(sklad_prerov['ID_komponenty']):
    if x in komp_prerov:
        sklad_prerov.iloc[index,2]=sklad_prerov.iloc[index,2]-komp_prerov[x]

for index,x in enumerate(sklad_ostrava['ID_komponenty']):
    if x in komp_ostrava:
        sklad_ostrava.iloc[index,2]=sklad_ostrava.iloc[index,2]-komp_ostrava[x]
sklad_prerov

    ID_skladu ID_komponenty  Mnozstvi Stav_ke_dni ID_zavodu
0        SK56         KO001        -4  2018-08-01      ZP20
2        SK56         KO044      -655  2018-08-01      ZP20
3        SK97         KO160       -92  2018-08-01      ZP20
13       SK56         KO159       -25  2018-08-01      ZP20
14       SK56         KO070        37  2018-08-01      ZP20
16       SK56         KO037      -103  2018-08-01      ZP20
19       SK97         KO193      -319  2018-08-01      ZP20
21       SK56         KO182      -158  2018-08-01      ZP20
22       SK97         KO145      -153  2018-08-01      ZP20
36       SK97         KO112         1  2018-08-01      ZP20
37       SK97         KO120       -72  2018-08-01      ZP20
38       SK56         KO110         2  2018-08-01      ZP20
39       SK56         KO205         1  2018-08-01      ZP20
40       SK56         KO046         4  2018-08-01      ZP20
43       SK56         KO003         5  2018-08-01      ZP20
44       SK97         KO004         1  2018-08-01      ZP20
51       SK56         KO206         4  2018-08-01      ZP20
76       SK56         ND101         1  2018-08-01      ZP20
77       SK56         ND103        27  2018-08-01      ZP20
78       SK97         ND104        34  2018-08-01      ZP20
79       SK97         ND105        16  2018-08-01      ZP20
80       SK56         ND106        14  2018-08-01      ZP20
81       SK97         ND107         6  2018-08-01      ZP20
82       SK97         ND108         6  2018-08-01      ZP20
83       SK97         ND110         6  2018-08-01      ZP20
84       SK97         ND111         7  2018-08-01      ZP20
85       SK56         ND112        12  2018-08-01      ZP20
86       SK97         ND113        16  2018-08-01      ZP20
87       SK56         ND115        27  2018-08-01      ZP20
88       SK97         ND116         2  2018-08-01      ZP20
89       SK97         ND117         4  2018-08-01      ZP20
90       SK97         ND118        25  2018-08-01      ZP20
91       SK56         ND119         9  2018-08-01      ZP20
92       SK56         ND120         3  2018-08-01      ZP20
93       SK97         ND123        30  2018-08-01      ZP20
94       SK56         ND124        18  2018-08-01      ZP20
114      SK97         ND114         9  2018-08-01      ZP20
115      SK56         ND121         2  2018-08-01      ZP20